### ISSUE TITLE
Roadmap to actually run a game

### ISSUE THREAD

**Issue by jeremyfa** [ceramic-engine/ceramic#1]
- [x] Display quads
- [x] Compute matrix from translation, scale, rotation, skewing on any visual
- [x] Compute display tree (visuals with children inherit transforms)
- [x] Use a flexible depth system instead of `setChildIndex()` hell
- [x] Macro based strictly typed event system
- [x] Macro based strictly typed entity-component system
- [x] Unified asset loader (load fonts, textures, texts, audio...)
- [x] Display images (quads with texture)
- [x] Premultiply textures (PNG) at compile time for best performances
- [x] Macro based lazy vars
- [x] Display text, with custom fonts
- [x] Implement screen scaling (FIT/FILL) and handle resizes
- [x] Manage texture densities (`@2x`, `@3x` ...) and update them as needed at runtime if the window size/density changes
- [x] Provide a default bitmap font
- [x] Add per-visual shaders
- [x] Configure default App Icons / Splash
- [x] Run Xcode iOS project from VSCode
- [x] Port Spine renderer from previous code base
- [x] Play sounds and background musics
- [x] Handle touch/mouse input
- [x] Display meshes (triangle vertices + uvs)
- [ ] Port iOS/Android sensors in backend
- [x] Improve Android/iOS automatic bindings
- [x] Plug gamepad API
- [ ] Implement Web sensors
- [x] Port `ceramic` command line utility
